begin;

create extension if not exists pgtap with schema extensions;

select plan(18);

select has_table(
  'public',
  'life_groups',
  'life_groups table exists'
);

select has_pk(
  'public',
  'life_groups',
  'life_groups has a primary key'
);

select col_type_is(
  'public',
  'life_groups',
  'id',
  'uuid',
  'life_groups.id is a uuid'
);

select col_type_is(
  'public',
  'life_groups',
  'leader_profile_id',
  'uuid',
  'life_groups.leader_profile_id is a uuid'
);

select is(
  (
    select relrowsecurity
    from pg_class
    where oid = 'public.life_groups'::regclass
  ),
  true,
  'life_groups has RLS enabled'
);

select ok(
  not has_table_privilege('anon', 'public.life_groups', 'select'),
  'anon has no direct life_groups access'
);

select ok(
  not has_table_privilege('authenticated', 'public.life_groups', 'select'),
  'authenticated has no direct life_groups access'
);

select is(
  (
    select count(*)
    from pg_policies
    where schemaname = 'public'
      and tablename = 'life_groups'
  ),
  0::bigint,
  'life_groups exposes no browser-facing RLS policies'
);

select ok(
  has_table_privilege('service_role', 'public.life_groups', 'select'),
  'service_role has server-side life_groups access'
);

insert into auth.users (id, email, raw_user_meta_data)
values
  (
    '31111111-1111-4111-8111-111111111111',
    'life-group-leader@example.test',
    '{"name":"Life Group Leader"}'::jsonb
  ),
  (
    '32222222-2222-4222-8222-222222222222',
    'second-leader@example.test',
    '{"name":"Second Leader"}'::jsonb
  );

insert into public.life_groups (name, description, leader_profile_id)
values (
  'North Life Group',
  'A test Life Group',
  '31111111-1111-4111-8111-111111111111'
);

select is(
  (
    select count(*)
    from public.life_groups
    where name = 'North Life Group'
      and leader_profile_id = '31111111-1111-4111-8111-111111111111'
  ),
  1::bigint,
  'a Life Group can reference an existing Profile'
);

select is(
  (select is_active from public.life_groups where name = 'North Life Group'),
  true,
  'new Life Groups default to active'
);

select ok(
  (select id is not null from public.life_groups where name = 'North Life Group'),
  'Life Group ids are generated by the database'
);

do $$
begin
  begin
    insert into public.life_groups (name, leader_profile_id)
    values ('   ', '32222222-2222-4222-8222-222222222222');

    raise exception 'blank Life Group name was accepted';
  exception
    when check_violation then null;
  end;
end;
$$;

select pass('blank Life Group names are rejected');

do $$
begin
  begin
    insert into public.life_groups (name, leader_profile_id)
    values ('Missing Leader Group', '39999999-9999-4999-8999-999999999999');

    raise exception 'invalid Leader Profile foreign key was accepted';
  exception
    when foreign_key_violation then null;
  end;
end;
$$;

select pass('an invalid Leader Profile foreign key is rejected');

do $$
begin
  begin
    insert into public.life_groups (name, leader_profile_id)
    values ('Duplicate Leader Group', '31111111-1111-4111-8111-111111111111');

    raise exception 'one Leader was assigned to multiple Life Groups';
  exception
    when unique_violation then null;
  end;
end;
$$;

select pass('one Leader cannot be assigned to multiple Life Groups');

do $$
begin
  begin
    insert into public.life_groups (name, leader_profile_id)
    values ('Missing Assignment Group', null);

    raise exception 'a Life Group without a Leader was accepted';
  exception
    when not_null_violation then null;
  end;
end;
$$;

select pass('every Life Group requires a Leader assignment');

update public.life_groups
set description = 'Updated description',
    updated_at = '2000-01-01 00:00:00+00'
where name = 'North Life Group';

select ok(
  (
    select updated_at > '2000-01-01 00:00:00+00'
    from public.life_groups
    where name = 'North Life Group'
  ),
  'updated_at is maintained by the database'
);

do $$
begin
  begin
    delete from auth.users
    where id = '31111111-1111-4111-8111-111111111111';

    raise exception 'an assigned Leader Profile was deleted';
  exception
    when foreign_key_violation then null;
  end;
end;
$$;

select pass('an assigned Leader Profile cannot be deleted without reassignment');

select * from finish();
rollback;
