begin;

create extension if not exists pgtap with schema extensions;

select plan(35);

select has_table('public', 'members', 'members table exists');
select has_pk('public', 'members', 'members has a primary key');
select col_type_is('public', 'members', 'id', 'uuid', 'members.id is a uuid');
select col_type_is(
  'public',
  'members',
  'life_group_id',
  'uuid',
  'members.life_group_id is a uuid'
);
select is(
  (
    select jsonb_agg(enumlabel order by enumsortorder)
    from pg_enum
    where enumtypid = 'public.member_gender'::regtype
  ),
  '["male", "female"]'::jsonb,
  'member_gender contains exactly male and female'
);
select is(
  (select relrowsecurity from pg_class where oid = 'public.members'::regclass),
  true,
  'members has RLS enabled'
);
select ok(
  not has_table_privilege('anon', 'public.members', 'select'),
  'anon has no direct members access'
);
select ok(
  not has_table_privilege('authenticated', 'public.members', 'select'),
  'authenticated has no direct members access'
);
select is(
  (
    select count(*)
    from pg_policies
    where schemaname = 'public' and tablename = 'members'
  ),
  0::bigint,
  'members exposes no browser-facing RLS policies'
);
select ok(
  has_table_privilege('service_role', 'public.members', 'select'),
  'service_role has server-side members access'
);
select ok(
  has_function_privilege(
    'service_role',
    'public.normalize_member_email(text)',
    'execute'
  ),
  'service_role can execute email normalization for generated columns'
);
select ok(
  has_function_privilege(
    'service_role',
    'public.normalize_member_phone(text)',
    'execute'
  ),
  'service_role can execute phone normalization for generated columns'
);

insert into auth.users (id, email, raw_user_meta_data)
values (
  '71111111-1111-4111-8111-111111111111',
  'members-leader@example.test',
  '{"name":"Members Leader"}'::jsonb
);

insert into public.life_groups (id, name, leader_profile_id)
values (
  '72222222-2222-4222-8222-222222222222',
  'Members Test Group',
  '71111111-1111-4111-8111-111111111111'
);

insert into public.members (
  first_name,
  last_name,
  phone,
  email,
  gender,
  life_group_id,
  qr_token
)
values (
  'Ana',
  'Santos',
  '0917 123 4567',
  ' Ana.Santos@Example.Test ',
  'female',
  '72222222-2222-4222-8222-222222222222',
  'member-token-1'
);

select is(
  (select count(*) from public.members where first_name = 'Ana'),
  1::bigint,
  'a valid Member can be created'
);
select is(
  (select is_active from public.members where qr_token = 'member-token-1'),
  true,
  'new Members default to active'
);
select ok(
  (select id is not null from public.members where qr_token = 'member-token-1'),
  'Member ids are generated by the database'
);
select is(
  (select normalized_email from public.members where qr_token = 'member-token-1'),
  'ana.santos@example.test',
  'email normalization trims and lowercases'
);
select is(
  (select normalized_phone from public.members where qr_token = 'member-token-1'),
  '639171234567',
  'Philippine mobile normalization uses the 639 canonical form'
);

do $$
begin
  begin
    insert into public.members (first_name, last_name, life_group_id, qr_token)
    values (' ', 'Valid', '72222222-2222-4222-8222-222222222222', 'blank-first');
    raise exception 'blank first name was accepted';
  exception when check_violation then null;
  end;
end;
$$;
select pass('blank first names are rejected');

do $$
begin
  begin
    insert into public.members (first_name, last_name, life_group_id, qr_token)
    values ('Valid', ' ', '72222222-2222-4222-8222-222222222222', 'blank-last');
    raise exception 'blank last name was accepted';
  exception when check_violation then null;
  end;
end;
$$;
select pass('blank last names are rejected');

do $$
begin
  begin
    insert into public.members (first_name, last_name, qr_token)
    values ('Missing', 'Group', 'missing-group');
    raise exception 'missing Life Group was accepted';
  exception when not_null_violation then null;
  end;
end;
$$;
select pass('every Member requires a Life Group');

do $$
begin
  begin
    insert into public.members (first_name, last_name, life_group_id, qr_token)
    values ('Bad', 'Group', '79999999-9999-4999-8999-999999999999', 'bad-group');
    raise exception 'invalid Life Group was accepted';
  exception when foreign_key_violation then null;
  end;
end;
$$;
select pass('an invalid Life Group foreign key is rejected');

insert into public.members (first_name, last_name, gender, life_group_id, qr_token)
values ('Male', 'Member', 'male', '72222222-2222-4222-8222-222222222222', 'male-token');
select is(
  (select gender::text from public.members where qr_token = 'male-token'),
  'male',
  'male is an accepted gender value'
);

insert into public.members (first_name, last_name, gender, life_group_id, qr_token)
values ('Female', 'Member', 'female', '72222222-2222-4222-8222-222222222222', 'female-token');
select is(
  (select gender::text from public.members where qr_token = 'female-token'),
  'female',
  'female is an accepted gender value'
);

do $$
begin
  begin
    insert into public.members (first_name, last_name, gender, life_group_id, qr_token)
    values ('Bad', 'Gender', 'other', '72222222-2222-4222-8222-222222222222', 'bad-gender');
    raise exception 'invalid gender was accepted';
  exception when invalid_text_representation then null;
  end;
end;
$$;
select pass('gender values outside male and female are rejected');

do $$
begin
  begin
    insert into public.members (first_name, last_name, life_group_id, qr_token)
    values ('Duplicate', 'Token', '72222222-2222-4222-8222-222222222222', 'member-token-1');
    raise exception 'duplicate QR token was accepted';
  exception when unique_violation then null;
  end;
end;
$$;
select pass('QR tokens are unique');

do $$
begin
  begin
    insert into public.members (first_name, last_name, email, life_group_id, qr_token)
    values ('Duplicate', 'Email', 'ANA.SANTOS@example.test', '72222222-2222-4222-8222-222222222222', 'email-token');
    raise exception 'normalized duplicate email was accepted';
  exception when unique_violation then null;
  end;
end;
$$;
select pass('normalized duplicate emails are rejected');

do $$
begin
  begin
    insert into public.members (first_name, last_name, phone, life_group_id, qr_token)
    values ('Duplicate', 'Phone', '+63 (917) 123-4567', '72222222-2222-4222-8222-222222222222', 'phone-token');
    raise exception 'normalized duplicate phone was accepted';
  exception when unique_violation then null;
  end;
end;
$$;
select pass('formatted Philippine duplicate phones are rejected');

insert into public.members (first_name, last_name, life_group_id, qr_token)
values
  ('No', 'Contact One', '72222222-2222-4222-8222-222222222222', 'null-contact-1'),
  ('No', 'Contact Two', '72222222-2222-4222-8222-222222222222', 'null-contact-2');
select is(
  (select count(*) from public.members where phone is null and email is null),
  4::bigint,
  'multiple Members may have null phone and email'
);

insert into public.members (first_name, last_name, life_group_id, qr_token)
values ('Ana', 'Santos', '72222222-2222-4222-8222-222222222222', 'duplicate-name');
select is(
  (select count(*) from public.members where first_name = 'Ana' and last_name = 'Santos'),
  2::bigint,
  'duplicate names are allowed'
);

update public.members set is_active = false where qr_token = 'member-token-1';
select is(
  (select is_active from public.members where qr_token = 'member-token-1'),
  false,
  'Member archive uses is_active false'
);
select is(
  (select qr_token from public.members where first_name = 'Ana' and email is not null),
  'member-token-1',
  'archive preserves the QR token'
);

update public.members
set address = 'Updated address', updated_at = '2000-01-01 00:00:00+00'
where qr_token = 'member-token-1';
select ok(
  (select updated_at > '2000-01-01 00:00:00+00' from public.members where qr_token = 'member-token-1'),
  'updated_at is maintained by the database'
);

update public.life_groups
set is_active = false
where id = '72222222-2222-4222-8222-222222222222';
select is(
  (select count(*) from public.members where life_group_id = '72222222-2222-4222-8222-222222222222'),
  6::bigint,
  'archiving a Life Group preserves existing Members'
);

do $$
begin
  begin
    delete from public.life_groups where id = '72222222-2222-4222-8222-222222222222';
    raise exception 'a referenced Life Group was deleted';
  exception when foreign_key_violation then null;
  end;
end;
$$;
select pass('a referenced Life Group cannot be deleted');

select is(
  public.normalize_member_phone('(02) 8123-4567'),
  '0281234567',
  'other phone formats use conservative digit normalization'
);

select * from finish();
rollback;
