begin;
select plan(23);
select has_table('public','opencell_programmes','programmes table exists');
select has_table('public','opencell_sessions','sessions table exists');
select has_table('public','opencell_enrollments','enrollments table exists');
select has_table('public','opencell_attendance','attendance table exists');
select has_type('public','opencell_programme_status','programme status enum exists');
select col_type_is('public','opencell_programmes','status','public.opencell_programme_status','programme status uses enum');
select col_default_is('public','opencell_programmes','status', 'active'::public.opencell_programme_status,'programmes start active');
select col_not_null('public','opencell_programmes','name','programme name required');
select col_not_null('public','opencell_sessions','programme_id','session programme required');
select col_not_null('public','opencell_enrollments','enrolled_on','enrollment date required');
select col_not_null('public','opencell_attendance','visitor_id','attendance visitor required');
select has_index('public','opencell_enrollments','opencell_enrollments_pkey','enrollment pair unique');
select has_index('public','opencell_attendance','opencell_attendance_pkey','attendance pair unique');
select has_function('public','enroll_opencell_visitor',array['uuid','uuid','date','uuid'],'enrollment function exists');
select has_function('public','remove_opencell_enrollment',array['uuid','uuid'],'enrollment removal function exists');
select has_function('public','finish_opencell_programme',array['uuid'],'finish function exists');
select ok(not has_table_privilege('anon','public.opencell_programmes','select'), 'browser cannot read programmes directly');
select ok(not has_table_privilege('authenticated','public.opencell_sessions','select'), 'browser cannot read sessions directly');
select ok(not has_table_privilege('authenticated','public.opencell_enrollments','insert'), 'browser cannot write enrollments directly');
select ok(not has_table_privilege('authenticated','public.opencell_attendance','insert'), 'browser cannot write attendance directly');
select throws_ok($$insert into public.opencell_programmes(name,created_by_profile_id) values ('', '00000000-0000-4000-8000-000000000000')$$, '23514');
select throws_ok($$insert into public.opencell_sessions(programme_id,session_date) values ('00000000-0000-4000-8000-000000000000', current_date)$$, '23503');
select pass('OpenCell lifecycle and integrity are enforced by service-role functions and restrictive foreign keys');
select * from finish();
rollback;
