import { Router, type Response } from "express";
import { requireAuth } from "../auth/middleware.js";
import type { AuthService } from "../auth/types.js";
import { OpenCellServiceError, type OpenCellService } from "../opencell/types.js";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function err(r:Response,s:number,c:string,m:string){r.status(s).json({error:{code:c,message:m}})}
function record(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v)}
function uid(v:unknown){return typeof v==="string"&&UUID.test(v)?v:undefined}
async function handle(r:Response,op:()=>Promise<unknown>,status=200){try{r.status(status).json({data:await op()})}catch(e){if(e instanceof OpenCellServiceError){err(r,e.status,e.code,e.message);return}err(r,500,"OPENCELL_SERVICE_UNAVAILABLE","OpenCell data is temporarily unavailable.")}}
function fields(body:Record<string,unknown>,allowed:string[]){return Object.keys(body).some(k=>!allowed.includes(k))}
function text(v:unknown,optional=true){if(v===undefined&&optional)return undefined;if(v===null&&optional)return null;return typeof v==="string"&&v.trim()?v.trim():undefined}
export function createOpenCellRouter(authService:AuthService,service:OpenCellService){const router=Router();const auth=requireAuth(authService);
 router.get("/opencell/programmes",auth,async(req,res)=>{if(!req.actor)return;const search=typeof req.query.search==="string"?req.query.search.trim():"";const status=req.query.status===undefined?"active":req.query.status;if(!["active","finished","all"].includes(String(status))){err(res,400,"INVALID_REQUEST","Status must be active, finished, or all.");return}await handle(res,()=>service.list(req.actor!,{search,status:status as "active"|"finished"|"all"}))});
 router.get("/opencell/programmes/:id",auth,async(req,res)=>{const id=uid(req.params.id);if(!id){err(res,400,"INVALID_REQUEST","Programme ID must be a valid UUID.");return}await handle(res,()=>service.getById(req.actor!,id))});
 router.post("/opencell/programmes",auth,async(req,res)=>{if(!req.actor||!record(req.body)||fields(req.body,["name","description"])){err(res,400,"INVALID_REQUEST","Provide only name and description.");return}const name=text(req.body.name,false);const description=text(req.body.description);if(!name||description===undefined){err(res,400,"INVALID_REQUEST","Programme name is required.");return}await handle(res,()=>service.create(req.actor!,{name,description}),201)});
 router.patch("/opencell/programmes/:id",auth,async(req,res)=>{const id=uid(req.params.id);if(!id||!record(req.body)||fields(req.body,["name","description"])) {err(res,400,"INVALID_REQUEST","Provide only name and description.");return}const input:{name?:string;description?:string|null}={};if(Object.prototype.hasOwnProperty.call(req.body,"name")){const n=text(req.body.name,false);if(!n){err(res,400,"INVALID_REQUEST","Programme name is required.");return}input.name=n}if(Object.prototype.hasOwnProperty.call(req.body,"description")){const d=text(req.body.description);if(d===undefined){err(res,400,"INVALID_REQUEST","Description must be text or null.");return}input.description=d}await handle(res,()=>service.update(req.actor!,id,input))});
 router.post("/opencell/programmes/:id/finish",auth,async(req,res)=>{const id=uid(req.params.id);if(!id){err(res,400,"INVALID_REQUEST","Programme ID must be a valid UUID.");return}await handle(res,()=>service.finish(req.actor!,id))});
 router.get("/opencell/programmes/:id/sessions",auth,async(req,res)=>{const id=uid(req.params.id);if(!id){err(res,400,"INVALID_REQUEST","Programme ID must be a valid UUID.");return}await handle(res,()=>service.listSessions(req.actor!,id))});
 router.post("/opencell/programmes/:id/sessions",auth,async(req,res)=>{const id=uid(req.params.id);if(!id||!record(req.body)||fields(req.body,["sessionDate","title","location","notes"])){err(res,400,"INVALID_REQUEST","Provide the approved Session fields.");return}const sessionDate=text(req.body.sessionDate,false);const title=text(req.body.title);const location=text(req.body.location);const notes=text(req.body.notes);if(!sessionDate||title===undefined||location===undefined||notes===undefined){err(res,400,"INVALID_REQUEST","Session date is required.");return}await handle(res,()=>service.createSession(req.actor!,id,{sessionDate,title,location,notes}),201)});
 router.patch("/opencell/programmes/:id/sessions/:sessionId",auth,async(req,res)=>{const id=uid(req.params.id),sessionId=uid(req.params.sessionId);if(!id||!sessionId||!record(req.body)||fields(req.body,["sessionDate","title","location","notes"])){err(res,400,"INVALID_REQUEST","Provide the approved Session fields.");return}const input:Record<string,string|null>={};for(const key of ["sessionDate","title","location","notes"]){if(Object.prototype.hasOwnProperty.call(req.body,key)){const value=req.body[key];if(key==="sessionDate"){const v=text(value,false);if(!v){err(res,400,"INVALID_REQUEST","Session date is required.");return}input[key]=v}else{const v=text(value);if(v===undefined){err(res,400,"INVALID_REQUEST","Session fields must be text or null.");return}input[key]=v}}}await handle(res,()=>service.updateSession(req.actor!,id,sessionId,input))});
 router.patch("/opencell/programmes/:id/sessions/:sessionId/cancel",auth,async(req,res)=>{const id=uid(req.params.id),sessionId=uid(req.params.sessionId);if(!id||!sessionId){err(res,400,"INVALID_REQUEST","IDs must be valid UUIDs.");return}await handle(res,()=>service.cancelSession(req.actor!,id,sessionId))});
 router.get("/opencell/programmes/:id/participants",auth,async(req,res)=>{const id=uid(req.params.id);if(!id){err(res,400,"INVALID_REQUEST","Programme ID must be a valid UUID.");return}await handle(res,()=>service.listParticipants(req.actor!,id))});
 router.post("/opencell/programmes/:id/participants",auth,async(req,res)=>{const id=uid(req.params.id);if(!id||!record(req.body)||fields(req.body,["visitorId","enrolledOn"])){err(res,400,"INVALID_REQUEST","Provide an existing Visitor and optional enrollment date.");return}const visitorId=uid(req.body.visitorId);const enrolledOn=req.body.enrolledOn===undefined?new Date().toISOString().slice(0,10):text(req.body.enrolledOn,false);if(!visitorId||!enrolledOn){err(res,400,"INVALID_REQUEST","Visitor ID and enrollment date are required.");return}await handle(res,()=>service.enroll(req.actor!,id,visitorId,enrolledOn),201)});
 router.delete("/opencell/programmes/:id/participants/:visitorId",auth,async(req,res)=>{const id=uid(req.params.id),visitorId=uid(req.params.visitorId);if(!id||!visitorId){err(res,400,"INVALID_REQUEST","IDs must be valid UUIDs.");return}await handle(res,()=>service.removeEnrollment(req.actor!,id,visitorId))});
 router.get("/opencell/programmes/:id/sessions/:sessionId/attendance",auth,async(req,res)=>{const id=uid(req.params.id),sessionId=uid(req.params.sessionId);if(!id||!sessionId){err(res,400,"INVALID_REQUEST","IDs must be valid UUIDs.");return}await handle(res,()=>service.listAttendance(req.actor!,id,sessionId))});
 router.post("/opencell/programmes/:id/sessions/:sessionId/attendance",auth,async(req,res)=>{const id=uid(req.params.id),sessionId=uid(req.params.sessionId),visitorId=record(req.body)?uid(req.body.visitorId):undefined;if(!id||!sessionId||!visitorId){err(res,400,"INVALID_REQUEST","Visitor ID is required.");return}await handle(res,()=>service.addAttendance(req.actor!,id,sessionId,visitorId),201)});
 router.delete("/opencell/programmes/:id/sessions/:sessionId/attendance/:visitorId",auth,async(req,res)=>{const id=uid(req.params.id),sessionId=uid(req.params.sessionId),visitorId=uid(req.params.visitorId);if(!id||!sessionId||!visitorId){err(res,400,"INVALID_REQUEST","IDs must be valid UUIDs.");return}await handle(res,()=>service.removeAttendance(req.actor!,id,sessionId,visitorId))});
 return router as Router;
}
