import { createClient } from "@supabase/supabase-js";
import request from "supertest";
import { afterEach, describe, expect, it } from "vitest";
import { createApp } from "../app.js";
import type { AuthService, HorizonActor } from "../auth/types.js";
import type { Database } from "../types/database.types.js";
import { createSupabaseOpenCellService } from "./supabase-opencell-service.js";

const url=process.env.SUPABASE_URL; const key=process.env.SUPABASE_SERVICE_ROLE_KEY; const suite=url&&key?describe:describe.skip;
suite("OpenCell API with local Supabase",()=>{const db=createClient<Database>(url??"http://127.0.0.1:54321",key??"missing",{auth:{autoRefreshToken:false,detectSessionInUrl:false,persistSession:false}});const users:string[]=[];const programmes:string[]=[];const visitors:string[]=[];const sessions:string[]=[];
 afterEach(async()=>{if(sessions.length)await db.from("opencell_sessions").delete().in("id",sessions.splice(0));if(programmes.length)await db.from("opencell_programmes").delete().in("id",programmes.splice(0));if(visitors.length){await db.from("follow_ups").delete().in("visitor_id",visitors);await db.from("visitors").delete().in("id",visitors.splice(0));}for(const id of users.splice(0).reverse())await db.auth.admin.deleteUser(id);});
 async function profile(){const {data,error}=await db.auth.admin.createUser({email:`oc-${Date.now()}@example.test`,email_confirm:true,password:"OpenCell-Aa1!"});if(error||!data.user)throw error??new Error("user missing");users.push(data.user.id);await db.from("profiles").update({role:"leader"}).eq("id",data.user.id);return data.user.id;}
 it("supports shared management, dated attendance, and one active enrollment",async()=>{const actorId=await profile();const actor:HorizonActor={id:actorId,isActive:true,name:"OpenCell Leader",role:"leader"};const auth:AuthService={authenticate:async()=>({ok:true,actor})};const service=createSupabaseOpenCellService({serviceRoleKey:key!,supabaseUrl:url!});const app=createApp({authService:auth,openCellService:service});const api=(method:"get"|"post",path:string)=>request(app)[method](path).set("Authorization","Bearer oc-token");const created=await api("post","/api/opencell/programmes").send({name:"Foundations",description:null});expect(created.status).toBe(201);const programmeId=created.body.data.id;programmes.push(programmeId);const visitor=await db.from("visitors").insert({first_name:"Open",last_name:"Cell",status:"active"}).select("id").single();if(visitor.error)throw visitor.error;visitors.push(visitor.data.id);const enrolled=await api("post",`/api/opencell/programmes/${programmeId}/participants`).send({visitorId:visitor.data.id,enrolledOn:"2026-09-01"});expect(enrolled.status).toBe(201);const duplicate=await api("post",`/api/opencell/programmes/${programmeId}/participants`).send({visitorId:visitor.data.id,enrolledOn:"2026-09-01"});expect(duplicate.status).toBe(409);const session=await api("post",`/api/opencell/programmes/${programmeId}/sessions`).send({sessionDate:"2026-09-02",title:"Week 1",location:null,notes:null});expect(session.status).toBe(201);sessions.push(session.body.data.id);const marked=await api("post",`/api/opencell/programmes/${programmeId}/sessions/${session.body.data.id}/attendance`).send({visitorId:visitor.data.id});expect(marked.status).toBe(201);const finished=await api("post",`/api/opencell/programmes/${programmeId}/finish`).send();expect(finished.status).toBe(200);expect(finished.body.data.evaluations[0]).toMatchObject({qualified:true,attendedCount:1,eligibleSessionCount:1});});
});
