/* eslint-disable @typescript-eslint/no-unused-vars */
import { createClient } from "@supabase/supabase-js";
import type { Database, Tables } from "../types/database.types.js";
import { OpenCellServiceError, type OpenCellEvaluation, type OpenCellProgramme, type OpenCellService, type OpenCellSession } from "./types.js";

interface Config { serviceRoleKey:string; supabaseUrl:string; }
const PROGRAMME_COLUMNS="id,name,description,status,created_by_profile_id,finished_at,created_at,updated_at";
const SESSION_COLUMNS="id,programme_id,session_date,title,location,notes,is_cancelled,created_at,updated_at";
function unavailable(){return new OpenCellServiceError(500,"OPENCELL_SERVICE_UNAVAILABLE","OpenCell data is temporarily unavailable.");}
function notFound(){return new OpenCellServiceError(404,"OPENCELL_NOT_FOUND","OpenCell record was not found.");}
function mapProgramme(row:Tables<"opencell_programmes">,sessionCount=0,participantCount=0):OpenCellProgramme{return {id:row.id,name:row.name,description:row.description,status:row.status,createdByProfileId:row.created_by_profile_id,finishedAt:row.finished_at,createdAt:row.created_at,updatedAt:row.updated_at,sessionCount,participantCount};}
function mapSession(row:Tables<"opencell_sessions">,attendanceCount=0):OpenCellSession{return {id:row.id,programmeId:row.programme_id,sessionDate:row.session_date,title:row.title,location:row.location,notes:row.notes,isCancelled:row.is_cancelled,createdAt:row.created_at,updatedAt:row.updated_at,attendanceCount};}
function churchToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
export function createSupabaseOpenCellService({serviceRoleKey,supabaseUrl}:Config):OpenCellService{
 const supabase=createClient<Database>(supabaseUrl,serviceRoleKey,{auth:{autoRefreshToken:false,detectSessionInUrl:false,persistSession:false}});
 async function programme(id:string){const {data,error}=await supabase.from("opencell_programmes").select(PROGRAMME_COLUMNS).eq("id",id).maybeSingle();if(error)throw unavailable();if(!data)throw notFound();return data;}
 async function activeProgramme(id:string){const row=await programme(id);if(row.status!=="active")throw new OpenCellServiceError(409,"PROGRAMME_FINISHED","Finished OpenCell Programmes are read-only.");return row;}
 async function session(programmeId:string,sessionId:string){const {data,error}=await supabase.from("opencell_sessions").select(SESSION_COLUMNS).eq("id",sessionId).eq("programme_id",programmeId).maybeSingle();if(error)throw unavailable();if(!data)throw new OpenCellServiceError(404,"SESSION_NOT_FOUND","Session was not found.");return data;}
 async function counts(ids:string[]){if(!ids.length)return new Map<string,[number,number]>();const [{data:s},{data:p}]=await Promise.all([supabase.from("opencell_sessions").select("programme_id").in("programme_id",ids),supabase.from("opencell_enrollments").select("programme_id").in("programme_id",ids)]);const result=new Map<string,[number,number]>();for(const id of ids)result.set(id,[0,0]);for(const row of s??[])result.get(row.programme_id)![0]++;for(const row of p??[])result.get(row.programme_id)![1]++;return result;}
 async function participantRows(programmeId:string){const {data,error}=await supabase.from("opencell_enrollments").select("programme_id,visitor_id,enrolled_on,visitors(id,first_name,last_name,email,phone,status)").eq("programme_id",programmeId);if(error)throw unavailable();return data??[];}
 return {
  async list(_actor,options){let q=supabase.from("opencell_programmes").select(PROGRAMME_COLUMNS).order("created_at",{ascending:false});if(options.status!=="all")q=q.eq("status",options.status);const {data,error}=await q;if(error)throw unavailable();const rows=data??[];const filtered=options.search?rows.filter(r=>r.name.toLocaleLowerCase().includes(options.search!.toLocaleLowerCase())):rows;const c=await counts(filtered.map(r=>r.id));return filtered.map(r=>mapProgramme(r,...(c.get(r.id)??[0,0])));},
  async getById(_actor,id){return mapProgramme(await programme(id));},
  async create(actor,input){const {data,error}=await supabase.from("opencell_programmes").insert({name:input.name,description:input.description,created_by_profile_id:actor.id}).select(PROGRAMME_COLUMNS).single();if(error)throw unavailable();return mapProgramme(data);},
  async update(_actor,id,input){await activeProgramme(id);const {data,error}=await supabase.from("opencell_programmes").update(input).eq("id",id).select(PROGRAMME_COLUMNS).single();if(error)throw unavailable();return mapProgramme(data);},
  async finish(_actor,id){const {data,error}=await supabase.rpc("finish_opencell_programme",{p_programme_id:id});if(error)throw unavailable();const result=data?.[0];if(!result)throw unavailable();if(result.outcome==="programme_not_found")throw notFound();if(result.outcome==="already_finished")throw new OpenCellServiceError(409,"PROGRAMME_FINISHED","This Programme has already been finished.");if(result.outcome!=="finished")throw unavailable();const row=await programme(id);const evaluations=Array.isArray(result.evaluations)?result.evaluations as unknown as OpenCellEvaluation[]:[];return {programme:mapProgramme(row),evaluations};},
  async listSessions(_actor,programmeId){await programme(programmeId);const {data,error}=await supabase.from("opencell_sessions").select(SESSION_COLUMNS).eq("programme_id",programmeId).order("session_date").order("id");if(error)throw unavailable();const rows=data??[];const ids=rows.map(r=>r.id);const {data:att}=ids.length?await supabase.from("opencell_attendance").select("session_id").in("session_id",ids):{data:[]};const c=new Map<string,number>();for(const a of att??[])c.set(a.session_id,(c.get(a.session_id)??0)+1);return rows.map(r=>mapSession(r,c.get(r.id)??0));},
  async createSession(_actor,programmeId,input){await activeProgramme(programmeId);const {data,error}=await supabase.from("opencell_sessions").insert({programme_id:programmeId,session_date:input.sessionDate,title:input.title,location:input.location,notes:input.notes}).select(SESSION_COLUMNS).single();if(error)throw unavailable();return mapSession(data);},
  async updateSession(_actor,programmeId,sessionId,input){await activeProgramme(programmeId);const current=await session(programmeId,sessionId);if(input.sessionDate!==undefined&&input.sessionDate!==current.session_date){const {count,error}=await supabase.from("opencell_attendance").select("session_id",{count:"exact",head:true}).eq("session_id",sessionId);if(error)throw unavailable();if((count??0)>0)throw new OpenCellServiceError(409,"SESSION_HAS_ATTENDANCE","Remove attendance before changing the Session date.");}const update={...(input.sessionDate!==undefined?{session_date:input.sessionDate}:{}),...(input.title!==undefined?{title:input.title}:{}),...(input.location!==undefined?{location:input.location}:{}),...(input.notes!==undefined?{notes:input.notes}:{})};const {data,error}=await supabase.from("opencell_sessions").update(update).eq("id",sessionId).select(SESSION_COLUMNS).single();if(error)throw unavailable();return mapSession(data);},
  async cancelSession(_actor,programmeId,sessionId){await activeProgramme(programmeId);await session(programmeId,sessionId);const {count,error}=await supabase.from("opencell_attendance").select("session_id",{count:"exact",head:true}).eq("session_id",sessionId);if(error)throw unavailable();if((count??0)>0)throw new OpenCellServiceError(409,"SESSION_HAS_ATTENDANCE","Correct attendance before cancelling this Session.");const {data:update,error:updateError}=await supabase.from("opencell_sessions").update({is_cancelled:true}).eq("id",sessionId).select(SESSION_COLUMNS).single();if(updateError)throw unavailable();return mapSession(update);},
  async listParticipants(_actor,programmeId){const p=await programme(programmeId);const rows=await participantRows(programmeId);const {data:sessions,error}=await supabase.from("opencell_sessions").select("id,session_date,is_cancelled").eq("programme_id",programmeId);if(error)throw unavailable();const ids=(sessions??[]).map(s=>s.id);const {data:attendance}=ids.length?await supabase.from("opencell_attendance").select("session_id,visitor_id").in("session_id",ids):{data:[]};return rows.map((row)=>{const visitor=Array.isArray(row.visitors)?row.visitors[0]:row.visitors;const eligible=(sessions??[]).filter(s=>!s.is_cancelled&&s.session_date>=row.enrolled_on);const attended=new Set((attendance??[]).filter(a=>a.visitor_id===row.visitor_id).map(a=>a.session_id));return {visitorId:row.visitor_id,firstName:visitor?.first_name??"Visitor",lastName:visitor?.last_name??"",email:visitor?.email??null,phone:visitor?.phone??null,visitorStatus:visitor?.status??"active",enrolledOn:row.enrolled_on,attendedCount:eligible.filter(s=>attended.has(s.id)).length,eligibleSessionCount:eligible.length};});},
  async enroll(_actor,programmeId,visitorId,enrolledOn){const {data,error}=await supabase.rpc("enroll_opencell_visitor",{p_programme_id:programmeId,p_visitor_id:visitorId,p_enrolled_on:enrolledOn||churchToday(),p_enrolled_by_profile_id:_actor.id});if(error?.code==="23505")throw new OpenCellServiceError(409,"ALREADY_ENROLLED","This Visitor is already enrolled in the Programme.");if(error)throw unavailable();const result=data?.[0];if(!result)throw unavailable();if(result.outcome==="programme_not_found")throw notFound();if(result.outcome==="programme_finished")throw new OpenCellServiceError(409,"PROGRAMME_FINISHED","Finished OpenCell Programmes are read-only.");if(result.outcome==="visitor_not_found")throw new OpenCellServiceError(404,"VISITOR_NOT_FOUND","Visitor was not found.");if(result.outcome==="visitor_not_active")throw new OpenCellServiceError(422,"VISITOR_NOT_ACTIVE","Only active Visitors may enroll.");if(result.outcome==="already_enrolled")throw new OpenCellServiceError(409,"ALREADY_ENROLLED","This Visitor is already enrolled in the Programme.");if(result.outcome==="active_enrollment")throw new OpenCellServiceError(409,"ACTIVE_ENROLLMENT","This Visitor is enrolled in another active Programme.");const rows=await this.listParticipants(_actor,programmeId);const found=rows.find(r=>r.visitorId===visitorId);if(!found)throw unavailable();return found;},
  async removeEnrollment(_actor,programmeId,visitorId){const {data,error}=await supabase.rpc("remove_opencell_enrollment",{p_programme_id:programmeId,p_visitor_id:visitorId});if(error)throw unavailable();const outcome=data as string;if(outcome==="programme_not_found")throw notFound();if(outcome==="programme_finished")throw new OpenCellServiceError(409,"PROGRAMME_FINISHED","Finished OpenCell Programmes are read-only.");if(outcome==="enrollment_not_found")throw new OpenCellServiceError(404,"ENROLLMENT_NOT_FOUND","Enrollment was not found.");if(outcome==="attendance_exists")throw new OpenCellServiceError(409,"SESSION_HAS_ATTENDANCE","Attendance exists; this historical enrollment cannot be removed.");if(outcome!=="removed")throw unavailable();},
  async listAttendance(_actor,programmeId,sessionId){await session(programmeId,sessionId);const {data,error}=await supabase.from("opencell_attendance").select("visitor_id").eq("session_id",sessionId);if(error)throw unavailable();const present=new Set((data??[]).map(a=>a.visitor_id));const participants=await this.listParticipants(_actor,programmeId);return participants.map(p=>({visitorId:p.visitorId,present:present.has(p.visitorId)}));},
  async addAttendance(_actor,programmeId,sessionId,visitorId){await activeProgramme(programmeId);const current=await session(programmeId,sessionId);if(current.is_cancelled)throw new OpenCellServiceError(409,"NOT_ELIGIBLE","Cancelled Sessions do not accept attendance.");const p=(await this.listParticipants(_actor,programmeId)).find(x=>x.visitorId===visitorId);if(!p)throw new OpenCellServiceError(422,"NOT_ELIGIBLE","Visitor is not enrolled in this Programme.");if(!p.enrolledOn||current.session_date<p.enrolledOn)throw new OpenCellServiceError(422,"NOT_ELIGIBLE","Visitor was enrolled after this Session.");const {error}=await supabase.from("opencell_attendance").insert({session_id:sessionId,visitor_id:visitorId});if(error?.code==="23505")return;if(error?.code==="23514")throw new OpenCellServiceError(422,"NOT_ELIGIBLE","Visitor is not eligible for this Session.");if(error)throw unavailable();},
  async removeAttendance(_actor,programmeId,sessionId,visitorId){await activeProgramme(programmeId);const {data,error}=await supabase.from("opencell_attendance").delete().eq("session_id",sessionId).eq("visitor_id",visitorId).select("visitor_id").maybeSingle();if(error)throw unavailable();if(!data)throw new OpenCellServiceError(404,"ATTENDANCE_NOT_FOUND","Attendance was not found.");},
 };
}
