create type public.member_gender as enum ('male', 'female');

create function public.normalize_member_email(value text)
returns text
language sql
immutable
strict
set search_path = ''
as $$
  select nullif(lower(btrim(value)), '');
$$;

create function public.normalize_member_phone(value text)
returns text
language sql
immutable
strict
set search_path = ''
as $$
  with normalized as (
    select nullif(regexp_replace(value, '[^0-9]', '', 'g'), '') as digits
  )
  select case
    when digits ~ '^09[0-9]{9}$' then '63' || substr(digits, 2)
    when digits ~ '^639[0-9]{9}$' then digits
    else digits
  end
  from normalized;
$$;

revoke all on function public.normalize_member_email(text)
from public, anon, authenticated;
revoke all on function public.normalize_member_phone(text)
from public, anon, authenticated;
grant execute on function public.normalize_member_email(text) to service_role;
grant execute on function public.normalize_member_phone(text) to service_role;

create table public.members (
  id uuid primary key default gen_random_uuid(),
  first_name text not null
    constraint members_first_name_not_blank check (btrim(first_name) <> ''),
  last_name text not null
    constraint members_last_name_not_blank check (btrim(last_name) <> ''),
  phone text
    constraint members_phone_not_blank check (phone is null or btrim(phone) <> ''),
  normalized_phone text generated always as (
    public.normalize_member_phone(phone)
  ) stored,
  email text
    constraint members_email_not_blank check (email is null or btrim(email) <> ''),
  normalized_email text generated always as (
    public.normalize_member_email(email)
  ) stored,
  address text,
  birth_date date,
  gender public.member_gender,
  life_group_id uuid not null
    constraint members_life_group_id_fkey
      references public.life_groups (id) on delete restrict,
  qr_token text not null
    constraint members_qr_token_not_blank check (btrim(qr_token) <> '')
    constraint members_qr_token_key unique,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index members_normalized_email_key
on public.members (normalized_email)
where normalized_email is not null;

create unique index members_normalized_phone_key
on public.members (normalized_phone)
where normalized_phone is not null;

create index members_life_group_id_idx
on public.members (life_group_id);

create index members_active_life_group_id_idx
on public.members (life_group_id)
where is_active;

comment on table public.members is
  'Horizon Members with one current Life Group and an archive-only lifecycle.';

comment on column public.members.normalized_email is
  'Generated lowercase/trimmed email used only for duplicate integrity.';

comment on column public.members.normalized_phone is
  'Generated digit-normalized phone used only for duplicate integrity.';

comment on column public.members.qr_token is
  'Permanent opaque token generated by Express; not derived from the Member UUID.';

comment on column public.members.is_active is
  'Archive lifecycle flag; normal product behavior does not hard-delete Members.';

alter table public.members enable row level security;

revoke all on table public.members from anon, authenticated;
grant select, insert, update, delete on table public.members to service_role;

create trigger set_members_updated_at
before update on public.members
for each row
execute function public.set_profiles_updated_at();
